export const CHAT_TOKENS = {
  CONVERSATION_REQUEST_REPOSITORY: Symbol('CONVERSATION_REQUEST_REPOSITORY'),
  CONVERSATION_REPOSITORY: Symbol('CONVERSATION_REPOSITORY'),
  MESSAGE_REPOSITORY: Symbol('MESSAGE_REPOSITORY'),
  MESSAGE_ATTACHMENT_REPOSITORY: Symbol('MESSAGE_ATTACHMENT_REPOSITORY'),
  CONVERSATION_READ_STATE_REPOSITORY: Symbol('CONVERSATION_READ_STATE_REPOSITORY'),
  FILE_STORAGE: Symbol('FILE_STORAGE'),
};
